[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$C2HMGYOQknKOEQJASElJaQ$VDIOPcNji2gxCDIN.TnPE/z3Ao9hZp.4Hc7C3xuUBBR.bZwlKeqZiY32rNuEVO8RVdqFm.hDzglnSMux4/R2QQ
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo123
log_level = info
